### ISSUE TITLE
[ERROR] can't convert vbox network to terraform data: No match with get guestproperty output

### ISSUE THREAD

**Issue by MuhanedYahya** [r0k5t4r/tf-vbox#1]
virtualbox version : v 6.1 
Ubuntu 20.4
Terraform v1.7.4 

╷
│ Error: [ERROR] can't convert vbox network to terraform data: No match with get guestproperty output
│ 
│   with virtualbox_vm.node[0],
│   on main.tf line 12, in resource "virtualbox_vm" "node":
│   12: resource "virtualbox_vm" "node" {
│ 
╵
╷
│ Error: [ERROR] can't convert vbox network to terraform data: No match with get guestproperty output
│ 
│   with virtualbox_vm.node[1],
│   on main.tf line 12, in resource "virtualbox_vm" "node":
│   12: resource "virtualbox_vm" "node" {
│ 
╵

**Comment by mango0422** [comment]
when i deleted metadatas about vagrant, i solved it.
but it was on windows11 with
Terraform v1.10.0-alpha20240828
on windows_amd64
+ provider registry.terraform.io/terra-farm/virtualbox v0.2.2-alpha.1
